services:
  - type: web
    name: ocean-finvest-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
    envVars:
      - key: TRUEDATA_USERNAME
        sync: false
      - key: TRUEDATA_PASSWORD
        sync: false
